/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaorderingsystem;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Margaux
 */
public class Register extends javax.swing.JFrame {

    public static int counter = 0;
    StringBuilder errors = new StringBuilder();

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    public boolean Firstname(String FirstName1) {
        if (FirstName1.isEmpty() || FirstName1.equals("First Name")) {
            errors.append("First Name field is Empty\n");
            return false;
        } else if (Pattern.matches("[a-zA-Z]+\\ [a-zA-Z]+|[a-zA-Z]+", FirstName1) == false) {
            errors.append("First Name field should only contain Letters and Without Spaces\n");
            return false;
        } else {
            return true;
        }
    }

    public boolean Lastname(String LastName1) {
        if (LastName1.isEmpty() || LastName1.equals("Last Name")) {
            errors.append("Last Name field is Empty\n");
            return false;
        } else if (Pattern.matches("[a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+", LastName1) == false) {
            errors.append("Last Name field should only contain Letters and Without Spaces\n Note: If you have Suffixes, you may only use one space and type in your Suffix");
            return false;
        } else {
            return true;
        }
    }

    public boolean Username(String UserName1) {
        if (UserName1.isEmpty() || UserName1.equals("Username")) {
            errors.append("Username is Empty\n");
            return false;
        } else if (Pattern.matches("[A-Za-z0-9+]{1,10}", UserName1) == false) {
            errors.append("Username should only have 10 characters\n");
            return false;
        } else {
            return true;
        }
    }

    public boolean Phone(String Phone1) {
        if (Phone1.isEmpty() || Phone1.equals("Phone")) {
            errors.append("Phone Field is Empty\n");
            return false;
        } else if (Pattern.matches("(^0|\\+63)[0-9+]{1,12}|[0-9+]{1,7}", Phone1) == false) {
            errors.append("Phone numbers should only contain either a 7 digit landline number or an 11 digit Mobile Number and Starts with either 0 or +63");
            return false;
        } else {
            return true;
        }
    }

    public boolean Password(String Password1) {
        if (Password1.isEmpty() || Password1.equals("Password")) {
            errors.append("Password Field is Empty");
            return false;
        } else if (Pattern.matches("[A-Za-z0-9+]{7,10}", Password1) == false) {
            errors.append("Password should contain only 7 characters and does not contain Special Characters");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Password.setBackground(new java.awt.Color(153, 0, 0));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setText("Password");
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password);
        Password.setBounds(420, 250, 270, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText(" tasty benefits and points you will be earning that you can use every time you dine with us");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 150, 560, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("In exchange, you will be able to taste not just our delicious pizza but also our");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 130, 480, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Try it now and experience the rich taste of Italian Pizza");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 90, 550, 40);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Want to become a member of Pizza Project?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 0, 540, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/pizzalogo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 187, 180);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("REGISTER NOW!");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 50, 190, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("ACCOUNT PASSWORD");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 210, 190, 30);

        Username.setBackground(new java.awt.Color(153, 0, 0));
        Username.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username.setText("Username ");
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username);
        Username.setBounds(10, 360, 270, 40);

        Phone.setBackground(new java.awt.Color(153, 0, 0));
        Phone.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Phone.setForeground(new java.awt.Color(255, 255, 255));
        Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Phone.setText("Phone");
        Phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhoneMouseClicked(evt);
            }
        });
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        jPanel1.add(Phone);
        Phone.setBounds(10, 310, 270, 40);

        FirstName.setBackground(new java.awt.Color(153, 0, 0));
        FirstName.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FirstName.setText("First Name");
        FirstName.setToolTipText("");
        FirstName.setName("First Name"); // NOI18N
        FirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstNameMouseClicked(evt);
            }
        });
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(FirstName);
        FirstName.setBounds(10, 250, 130, 40);

        LastName.setBackground(new java.awt.Color(153, 0, 0));
        LastName.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LastName.setText("Last Name");
        LastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastNameMouseClicked(evt);
            }
        });
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        jPanel1.add(LastName);
        LastName.setBounds(150, 250, 130, 40);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("ACCOUNT DETAILS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 210, 170, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("To register an account please fill out the following information below:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 180, 420, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 370, 150, 50);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 440, 55, 23);

        jTextField1.setBackground(new java.awt.Color(153, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Confirm Password");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(420, 300, 270, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 630, 330);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 320, 630, 160);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(620, 350, 140, 140);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        jLabel14.setText("jLabel13");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(620, 0, 140, 140);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        jLabel15.setText("jLabel13");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(620, 0, 140, 140);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        jLabel16.setText("jLabel13");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(620, 130, 140, 140);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        jLabel17.setText("jLabel13");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(620, 270, 140, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String FirstName1 = FirstName.getText();
        String LastName1 = LastName.getText();
        String UserName1 = Username.getText();
        String Password1 = Password.getText();
        String Checker = jTextField1.getText();
        String Phone1 = Phone.getText();
        File file = new File("C:\\Users\\Asus\\Downloads\\Compressed\\PizzaOrderingSystem\\src\\pizzaorderingsystem\\Registry.txt");
        try {
            if (Firstname(FirstName1) == false || Lastname(LastName1) == false || Phone(Phone1) == false
                    || Username(UserName1) == false || Password(Password1) == false || Checker.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, errors);
                errors.delete(0, errors.length());
            } else {
                if (Checker.equals(Password1)) {
                    BufferedWriter write = new BufferedWriter(new FileWriter(file, true));
                    write.write(FirstName1 + ";");
                    write.write(LastName1 + ";");
                    write.write(Phone1 + ";");
                    write.write(UserName1 + ";");
                    write.write(Password1 + ";");
                    write.write("0");
                    write.newLine();
                    write.close();
                    JOptionPane.showMessageDialog(rootPane, "You are now Registered! Proceed to Log In");
                    this.setVisible(false);
                    new MainMenu().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Confirmation Password does not match");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Input");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        Password.setText("");
    }//GEN-LAST:event_PasswordMouseClicked

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        Username.setText("");
    }//GEN-LAST:event_UsernameMouseClicked

    private void PhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhoneMouseClicked
        Phone.setText("");
    }//GEN-LAST:event_PhoneMouseClicked

    private void LastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastNameMouseClicked
        LastName.setText("");
    }//GEN-LAST:event_LastNameMouseClicked

    private void FirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameMouseClicked
        FirstName.setText("");
    }//GEN-LAST:event_FirstNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
