/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaorderingsystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class SummaryOfOrdersPremade extends javax.swing.JFrame {
    public static int userpointindex=0;
    public static int Order=0;
    /**
     * Creates new form SummaryOfOrders1
     */
    public SummaryOfOrdersPremade() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 410, 290);

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("NO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 520, 50, 23);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("YES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(141, 520, 60, 23);

        logo.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        logo.setForeground(new java.awt.Color(204, 0, 0));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/pizzalogo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 0, 190, 180);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Do you want to proceed on baking your masterpizza?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 490, 430, 30);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Summary Of Orders");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 40, 250, 70);

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        Background2.setText("jLabel4");
        jPanel1.add(Background2);
        Background2.setBounds(0, 280, 450, 280);

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaorderingsystem/woodenbackground.jpg"))); // NOI18N
        Background1.setText("jLabel4");
        jPanel1.add(Background1);
        Background1.setBounds(0, 0, 450, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new CustomizePizza().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String file = "C:\\Users\\Asus\\Downloads\\Compressed\\PizzaOrderingSystem\\src\\pizzaorderingsystem\\OrderSummaryPreMade.txt";
        
        try {
            BufferedWriter variable = new BufferedWriter(new FileWriter(file, true));
           variable.write(Order+";"+PizzaMenu.adminorder+"");
           variable.newLine();
           variable.close();
           if(Login.logincondition==true){
               String userfile="C:\\Users\\Asus\\Downloads\\Compressed\\PizzaOrderingSystem\\src\\pizzaorderingsystem\\Registry.txt";
               try {
                   BufferedReader read= new BufferedReader(new FileReader(userfile));
                   String line=null;
                   while((line=read.readLine())!=null){
                       String []values=line.split(";");
                       if(Login.UserIndex==userpointindex){
                           JOptionPane.showMessageDialog(rootPane, "Thank you for Ordering Sir/Ma'am: "+values[0]
                                   +"\n Once You have paid your Balance, Your points will be Automatically added!");
                       }
                       userpointindex++;
                   }
               } catch (Exception e) {
               }
           }else{
               JOptionPane.showMessageDialog(rootPane,"Order Recorded!");
           }
        } catch (Exception e) {
           System.out.println("An exception occured" );
        }
        Order++;
        this.setVisible(false);
        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1AncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
            throws IOException {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SummaryOfOrdersPremade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Background2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
